import bcryptjs from 'bcryptjs';

const data = {
    users: [
        {
            name: 'user1',
            email: 'user1@gmail.com',
            password: bcryptjs.hashSync('user1'),
            isAdmin: false,
        },
        {
            name: 'user2',
            email: 'user2@gmail.com',
            password: bcryptjs.hashSync('user2'),
            isAdmin: false,
        },
        {
            name: 'user3',
            email: 'user3@gmail.com',
            password: bcryptjs.hashSync('user3'),
            isAdmin: false,
        },
        {
            name: 'user4',
            email: 'user4@gmail.com',
            password: bcryptjs.hashSync('user4'),
            isAdmin: false,
        },
        {
            name: 'user5',
            email: 'user5@gmail.com',
            password: bcryptjs.hashSync('user5'),
            isAdmin: false,
        },
        {
            name: 'user6',
            email: 'user6@gmail.com',
            password: bcryptjs.hashSync('user6'),
            isAdmin: false,
        },
        {
            name: 'admin1',
            email: 'admin1@gmail.com',
            password: bcryptjs.hashSync('admin1'),
            isAdmin: true,
        },
        {
            name: 'admin2',
            email: 'admin2@gmail.com',
            password: bcryptjs.hashSync('admin2'),
            isAdmin: true,
        },
        
    ],
    products: [
        {
            name: 'iphone 14',
            slug: 'iphone-14',
            category: 'Phones',
            image: '/images/p4.jpg',
            price: 1100,
            countInStock: 5,
            brand: 'Apple',
            rating: 4.7,
            numReviews: 423,
            description: 'brand new iphone14 with discount',
        },

        {
            name: 'iPhone 13 Pro Max 128GB',
            slug: 'iPhone 13 Pro Max 128GB',
            category: 'iPhone',
            image: '/images/iphone-13-pro-max-silver.jpg',
            price: 750,
            countInStock: 7,
            brand: 'Apple',
            rating: 4.6,
            numReviews: 371,
            description: '99% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone 13 128GB Midnight',
            slug: 'iPhone 13 128GB Midnight',
            category: 'iPhone',
            image: '/images/iphone-13-midnight.jpg',
            price: 550,
            countInStock: 3,
            brand: 'Apple',
            rating: 4.2,
            numReviews: 72,
            description: '95% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone 13 128GB',
            slug: 'iPhone 13 128GB',
            category: 'iPhone',
            image: '/images/iphone-13-pink.jpg',
            price: 500,
            countInStock: 3,
            brand: 'Apple',
            rating: 5,
            numReviews: 31,
            description: '99% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {

            name: 'iPhone 12 64GB',
            slug: 'iPhone 12 64GB',
            category: 'iPhone',
            image: '/images/iphone-12-white.jpg',
            price: 323,
            countInStock: 7,
            brand: 'Apple',
            rating: 4.2,
            numReviews: 59,
            description: '98% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone X 64GB Space Gray',
            slug: 'iPhone X 64GB Space Gray',
            category: 'iPhone',
            image: '/images/iphone-x-space-gray-front.jpg',
            price: 250,
            countInStock: 7,
            brand: 'Apple',
            rating: 3.8,
            numReviews: 398,
            description: '88% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {

            name: 'iPhone 12 mini 64GB',
            slug: 'iPhone 12 mini 64GB',
            category: 'iPhone',
            image: '/images/iphone-12-mini-green.jpg',
            price: 288,
            countInStock: 5,
            brand: 'Apple',
            rating: 3.1,
            numReviews: 34,
            description: '85% new.Free delivery.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone 11 64GB Black',
            slug: 'iPhone 11 64GB Black',
            category: 'iPhone',
            image: '/images/iphone-11-black.jpg',
            price: 265,
            countInStock: 3,
            brand: 'Apple',
            rating: 2.4,
            numReviews: 77,
            description: '80% new.iPhone 11 64GB Black.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone 8 64GB',
            slug: 'iPhone 8 64GB',
            category: 'iPhone',
            image: '/images/iphone-8-space-gray.jpg',
            price: 265,
            countInStock: 3,
            brand: 'Apple',
            rating: 2.4,
            numReviews: 77,
            description: '75% new.iPhone 8 64GB.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPhone 8 Plus 256GB Silver',
            slug: 'iPhone 8 Plus 256GB Silver',
            category: 'iPhone',
            image: '/images/iphone-8-plus-silver.jpg',
            price: 230,
            countInStock: 2,
            brand: 'Apple',
            rating: 4.4,
            numReviews: 98,
            description: '85% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'AirPods Pro 1',
            slug: 'AirPods Pro 1',
            category: 'AirPods',
            image: '/images/airpods-pro-white.jpg',
            price: 150,
            countInStock: 2,
            brand: 'Apple',
            rating: 3.4,
            numReviews: 43,
            description: '85% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'AirPods Pro 2',
            slug: 'AirPods Pro 2',
            category: 'AirPods',
            image: '/images/airpods-pro-white.jpg',
            price: 250,
            countInStock: 2,
            brand: 'Apple',
            rating: 3.8,
            numReviews: 61,
            description: '85% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'AirPods Max Silver',
            slug: 'AirPods Max Silver',
            category: 'AirPods',
            image: '/images/airpods-max-silver.jpg',
            price: 800,
            countInStock: 2,
            brand: 'Apple',
            rating: 4.8,
            numReviews: 70,
            description: '85% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad 9 64GB Wifi Space Gray',
            slug: 'iPad 9 64GB Wifi Space Gray',
            category: 'iPad',
            image: '/images/ipad-9th-generation-space-gray.jpg',
            price: 380,
            countInStock: 2,
            brand: 'Apple',
            rating: 3.8,
            numReviews: 21,
            description: '85% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad 9 256GB Wifi Space Gray',
            slug: 'iPad 9 256GB Wifi Space Gray',
            category: 'iPad',
            image: '/images/ipad-9th-generation-space-gray.jpg',
            price: 460,
            countInStock: 2,
            brand: 'Apple',
            rating: 4.2,
            numReviews: 70,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad 8 128GB Wifi Space Gray',
            slug: 'iPad 8 128GB Wifi Space Gray',
            category: 'iPad',
            image: '/images/ipad-9th-generation-space-gray.jpg',
            price: 360,
            countInStock: 2,
            brand: 'Apple',
            rating: 3.9,
            numReviews: 371,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad 7 128GB Wifi Space Gray',
            slug: 'iPad 7 128GB Wifi Space Gray',
            category: 'iPad',
            image: '/images/ipad-9th-generation-space-gray.jpg',
            price: 290,
            countInStock: 2,
            brand: 'Apple',
            rating: 3.3,
            numReviews: 12,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S21 5G 128GB Phantom Gray',
            slug: 'Galaxy S21 5G 128GB Phantom Gray',
            category: 'Samsung Galaxy S21',
            image: '/images/galaxy-s21-phantom-gray.jpg',
            price: 350,
            countInStock: 2,
            brand: 'Samsung',
            rating: 4.8,
            numReviews: 85,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S21 5G 128GB Phantom Pink',
            slug: 'Galaxy S21 5G 128GB Phantom Pink',
            category: 'Samsung Galaxy S21',
            image: '/images/galaxy-s21-phantom-pink.jpg',
            price: 350,
            countInStock: 2,
            brand: 'Samsung',
            rating: 4.2,
            numReviews: 99,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S22 5G 128GB Phantom Black',
            slug: 'Galaxy S22 5G 128GB Phantom Black',
            category: 'Samsung Galaxy S22',
            image: '/images/galaxy-s22-phantom-black.jpg',
            price: 520,
            countInStock: 4,
            brand: 'Samsung',
            rating: 4.9,
            numReviews: 108,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S22 5G 256GB Phantom Black',
            slug: 'Galaxy S22 5G 256GB Phantom Black',
            category: 'Samsung Galaxy S22',
            image: '/images/galaxy-s22-phantom-black.jpg',
            price: 700,
            countInStock: 8,
            brand: 'Samsung',
            rating: 4.2,
            numReviews: 11,
            description: '95% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S21+ 5G 128GB Phantom Black',
            slug: 'Galaxy S21+ 5G 128GB Phantom Black',
            category: 'Samsung Galaxy S21+',
            image: '/images/galaxy-s21-plus-phantom-black.jpg',
            price: 370,
            countInStock: 5,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 82,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'Galaxy S20+ 128GB Cosmic Gray',
            slug: 'Galaxy S20+ 128GB Cosmic Gray',
            category: 'Samsung Galaxy S20+',
            image: '/images/galaxy-s20-plus-cosmic-gray.jpg',
            price: 310,
            countInStock: 5,
            brand: 'Samsung',
            rating: 4.4,
            numReviews: 9,
            description: '90% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad mini 5 64GB Wifi Silver (2019)',
            slug: 'iPad mini 5 64GB Wifi Silver (2019)',
            category: 'iPad',
            image: '/images/ipad-mini-5th-generation-silver.jpg',
            price: 485,
            countInStock: 4,
            brand: 'Apple',
            rating: 4.8,
            numReviews: 362,
            description: '95% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad mini 4 128GB Wifi Silver (2019)',
            slug: 'iPad mini 4 128GB Wifi Silver (2019)',
            category: 'iPad',
            image: '/images/ipad-mini-5th-generation-silver.jpg',
            price: 380,
            countInStock: 4,
            brand: 'Samsung',
            rating:3.8,
            numReviews: 66,
            description: '95% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad mini 3 64GB Wifi Silver (2019)',
            slug: 'iPad mini 3 64GB Wifi Silver (2019)',
            category: 'iPad',
            image: '/images/ipad-mini-5th-generation-silver.jpg',
            price: 300,
            countInStock: 4,
            brand: 'Samsung',
            rating: 3.4,
            numReviews: 87,
            description: '95% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'iPad Air 2 16GB Wifi Silver (2014)',
            slug: 'iPad Air 2 16GB Wifi Silver (2014)',
            category: 'iPad',
            image: '/images/ipad-air-2-silver.jpg',
            price: 300,
            countInStock: 4,
            brand: 'Samsung',
            rating: 4.4,
            numReviews: 17,
            description: '95% new.Delivered within 4 to 6 working days.Satisfied or refunded for 30 days. ',
        },
        {
            name: 'HP All-in-One 2022',
            slug: 'HP All-in-One 2022',
            category: 'Desktop Computer',
            image: '/images/hp1.jpg',
            price: 434,
            countInStock: 4,
            brand: 'Samsung',
            rating: 4.9,
            numReviews: 829,
            description: 'HP 2022 Newest All-in-One Desktop, 21.5" FHD Display, Intel Celeron J4025 Processor, 16GB RAM, 512GB PCIe SSD,  ',
        },
        {
            name: 'HP All-in-One 2022',
            slug: 'HP All-in-One 2022',
            category: 'Desktop Computer',
            image: '/images/hp1.jpg',
            price: 434,
            countInStock: 4,
            brand: 'HP',
            rating: 4.9,
            numReviews: 829,
            description: 'HP 2022 Newest All-in-One Desktop, 21.5" FHD Display, Intel Celeron J4025 Processor, 16GB RAM, 512GB PCIe SSD,  ',
        },
        {
            name: 'Dell OptiPlex Computer Desktop PC',
            slug: 'Dell OptiPlex Computer Desktop PC',
            category: 'Desktop Computer',
            image: '/images/Dell1.jpg',
            price: 187,
            countInStock: 4,
            brand: 'Dell',
            rating: 4.5,
            numReviews: 527,
            description: 'Dell OptiPlex Computer Desktop PC, Intel Core i5 3rd Gen 3.2 GHz, 16GB RAM,',
        },
        {
            name: 'Lenovo IdeaCentre AIO 3i',
            slug: 'Lenovo IdeaCentre AIO 3i',
            category: 'Desktop Computer',
            image: '/images/lenova1.jpg',
            price: 1200,
            countInStock: 4,
            brand: 'Dell',
            rating: 4.9,
            numReviews: 743,
            description: 'Lenovo IdeaCentre AIO 3i - 2022 - All-in-One Desktop - 27" FHD Touch Display - 5MP Camera - Windows 11 Home - 8GB Memory - 512GB Storage - Intel Core i5-1240P - Black - Mouse & Keyboard Included',
        },





        {
            name: 'Microsoft - Surface Pro',
            slug: 'Microsoft - Surface Pro',
            category: 'Desktop Computer',
            image: '/images/hp3.jpg',
            price: 1499,
            countInStock: 4,
            brand: 'Microsoft',
            rating: 4.7,
            numReviews: 886,
            description: 'Microsoft - Surface Pro - Copilot+ PC - 13” OLED - Snapdragon X Elite - 16GB Memory - 512GB SSD',
        },

        {
            name: 'Samsung - Galaxy Book4',
            slug: 'Samsung - Galaxy Book4',
            category: 'Laptop',
            image: '/images/laptop2.jpg',
            price: 549,
            countInStock: 8,
            brand: 'Samsung',
            rating: 3.8,
            numReviews: 168,
            description: 'Samsung - Galaxy Book4 15.6" FHD Laptop - Intel Core 7- 16GB Memory - 512GB SSD - Silver',
        },


        {
            name: 'Galaxy S9 64GB Midnight Black',
            slug: 'Galaxy S9 64GB Midnight Black',
            category: 'Samsung Galaxy S9',
            image: '/images/galaxy-s9-midnight-black.jpg',
            price: 1200,
            countInStock: 4,
            brand: 'Samsung',
            rating: 4.9,
            numReviews: 743,
            description: 'Lenovo IdeaCentre AIO 3i - 2022 - All-in-One Desktop - 27" FHD Touch Display - 5MP Camera - Windows 11 Home - 8GB Memory - 512GB Storage - Intel Core i5-1240P - Black - Mouse & Keyboard Included',
        },

        {
            name: 'Apple - MacBook Air 13.6" Laptop',
            slug: 'Apple - MacBook Air 13.6" Laptop',
            category: 'MacBook Air',
            image: '/images/macbook1.jpg',
            price: 799,
            countInStock: 7,
            brand: 'Apple',
            rating: 4.4,
            numReviews: 999,
            description: 'Apple - MacBook Air 13.6" Laptop - M2 chip - 8GB Memory - 256GB SSD - Midnight',
        },
        {
            name: 'Samsung - 65" Class QN90C Neo QLED',
            slug: 'Samsung - 65" Class QN90C Neo QLED',
            category: 'TV',
            image: '/images/tv1.jpg',
            price: 1297,
            countInStock: 7,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 739,
            description: 'Samsung - 65" Class QN90C Neo QLED 4K UHD Smart Tizen TV (2023)',
        },
        {
            name: 'Canon - EOS R6 Mark II Mirrorless Camera',
            slug: 'Canon - EOS R6 Mark II Mirrorless Camera',
            category: 'Camera',
            image: '/images/camera1.jpg',
            price: 1999,
            countInStock: 7,
            brand: 'Canon',
            rating: 4.9,
            numReviews: 625,
            description: 'Canon - EOS R6 Mark II Mirrorless Camera (Body Only) - Black',
        },
        {
            name: 'Sony - XG300 Bluetooth Speaker',
            slug: 'Sony - XG300 Bluetooth Speaker',
            category: 'Bluetooth Speaker',
            image: '/images/camera1.jpg',
            price: 159,
            countInStock: 7,
            brand: 'Sony',
            rating: 3.3,
            numReviews: 76,
            description: 'Sony - XG300 Portable Waterproof and Dustproof Bluetooth Speaker - Black',
        },
        {
            name: 'Fitbit - Inspire 3 Health & Fitness Tracker',
            slug: 'Fitbit - Inspire 3 Health & Fitness Tracker',
            category: 'Fitness Tracker',
            image: '/images/fitbit1.jpg',
            price: 79,
            countInStock: 7,
            brand: 'Fitbit',
            rating: 2.8,
            numReviews: 1672,
            description: 'Fitbit - Inspire 3 Health & Fitness Tracker',
        },
        {
            name: 'Logitech -Wireless Optical Gaming Mouse',
            slug: 'Logitech -Wireless Optical Gaming Mouse',
            category: 'Gaming Mouse',
            image: '/images/mouse1.jpg',
            price: 119,
            countInStock: 7,
            brand: 'Logitech',
            rating: 3.9,
            numReviews: 425,
            description: 'Logitech - PRO X SUPERLIGHT Lightweight Wireless Optical Gaming Mouse with HERO 25K Sensor - White',
        },
    ],
}

export default data;